comment:
  layout: "diff, files, footer"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
ignore:
  - "internal/models/**"
  - "tests/**"
  - "migrations/**"
  - "**/mocks/**"
