version: "3.9"
services:
  estrys:
    build: .
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  redis:
    image: redis:7.0
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 1s
      retries: 30
  db:
    image: postgres:15
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - .docker/db:/var/lib/postgresql
    environment:
      POSTGRES_USER: estrys
      PGUSER: estrys # for the healthcheck
      POSTGRES_PASSWORD: estrys
