// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	asynq "github.com/hibiken/asynq"

	mock "github.com/stretchr/testify/mock"
)

// BackgroundWorkerClient is an autogenerated mock type for the BackgroundWorkerClient type
type BackgroundWorkerClient struct {
	mock.Mock
}

// Enqueue provides a mock function with given fields: task, opts
func (_m *BackgroundWorkerClient) Enqueue(task *asynq.Task, opts ...asynq.Option) (*asynq.TaskInfo, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, task)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *asynq.TaskInfo
	if rf, ok := ret.Get(0).(func(*asynq.Task, ...asynq.Option) *asynq.TaskInfo); ok {
		r0 = rf(task, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*asynq.TaskInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*asynq.Task, ...asynq.Option) error); ok {
		r1 = rf(task, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBackgroundWorkerClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewBackgroundWorkerClient creates a new instance of BackgroundWorkerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBackgroundWorkerClient(t mockConstructorTestingTNewBackgroundWorkerClient) *BackgroundWorkerClient {
	mock := &BackgroundWorkerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
