name: docker
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build the Docker image
        run: DOCKER_BUILDKIT=1 docker build -t ghcr.io/estrys/estrys .
      - name: Push
        run: docker push ghcr.io/estrys/estrys